title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
              - name: Resize images
                uses: gonzalonaveira/gh-image-resizing@v1.0.2
            
